[package]
name = "leptos-mview-core"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
syn = { version = "2", features = ["extra-traits", "full"] }
quote = "1"
proc-macro2 = "1"
proc-macro-error = "1"
